### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by shirazz** [eugene-manuilov/react-gettext#14]
While running `npm start`.  The preset used in webpack config is `react`

**Comment by eugene-manuilov** [comment]
Hi @shirazz,

there is no `start` command in this repo. Does it happen when you run `npm start` in your project? Do you have `babel-preset-es2015` dependency there?

**Comment by shirazz** [comment]
@eugene-manuilov i am trying to run the sample app.

**Comment by eugene-manuilov** [comment]
Weird issue... but it seems to be gone after I have added babelrc file with es2015 preset. Could you please pull the latest version, reinstall dependencies and try again?

**Comment by shirazz** [comment]
Now its working fine. I was able to make it work by running the `npm i` on the root folder and then running again on the `examples/poedit` folder. Tried with the same fix which you have done and its was working 👍  Thank you.
