### ISSUE TITLE
How the new react context api affects react-gettext

### ISSUE THREAD

**Issue by shirazz** [eugene-manuilov/react-gettext#18]
I think we have to update the library in such a way that it will work with both versions of react. Means 16.3.0 as well as the pervious ones. Any suggestions on where we should start.

**Comment by eugene-manuilov** [comment]
Hey @shirazz,

yes, it is a good idea. I haven't looked at it yet, thus can't say anything specific yet. I'll try to find a time to look at it on next week. If you have already checked it and have ideas, then your pull request will be more than a welcome!

**Comment by bumpah** [comment]
Any updates according to new Context API and migrating to using that? 

I might try and look in to this on upcoming weekend.

**Comment by shirazz** [comment]
@bumpah did you get a chance to have a look at this. I can also help you as i think it is a nice thing to have.

**Comment by bumpah** [comment]
@shirazz still haven't had opportunity to look into this. i'll try asap to reserve sometime to this also.

**Comment by bumpah** [comment]
@shirazz I'll take some time this evening to look into what would needed to be done.

**Comment by bumpah** [comment]
I've made some research and plans how to migrate towards using new context API and will try complete this during upcoming weekend.

**Comment by shirazz** [comment]
Would you mind sharing your findings Jimi.

FRONTEND DEVELOPER
Shiraz Samad
shirazwaits@gmail.com
shirazsamad  Skype


Linkedin :  Shirazsamad
Twitter    :  Shirazz
Facebok  :  Shiraz.samad
Mobile     :  971-569240260

**Comment by eugene-manuilov** [comment]
Hey everyone! A new version (1.0.0) has been published that uses new Context API.

I am closing this thread for now. Feel free to open a new issue if you have troubles with the new version.
