### ISSUE TITLE
How to access context/state inside getTranslations() function

### ISSUE THREAD

**Issue by OsamaShabrez** [eugene-manuilov/react-gettext#6]
I followed the guide and everything works but I am still confused how can I implement multi-lingual react application.

The docs say, getTranslations() function should **returns hash object where keys are original messages and values are translated messages** but what should be the structure of this hash object when you have to distinguish between multiple locales (how to access locales in the function which are stored inside the state) and different contexts?

Thanks.

**Comment by eugene-manuilov** [comment]
Hey @OsamaShabrez,

thanks for reaching out. I have created an example which you can use on your end to better understand how to build multi-lingual app with this package. It is a React + React-Router application which loads appropriate translations based on current URL.

See it [here](https://github.com/eugene-manuilov/react-gettext/tree/release/0.3.2/examples/poedit) and let me know if you still have questions.

**Comment by inoas** [comment]
As for the context in `Textdomain.js` it seemed to me that the context is simply prepended to the message key:
```javascript
// in react-gettext: Textdomain.js
var key = context + EOT + message;
return Object.prototype.hasOwnProperty.call(messages, key) ? messages[key] : message;
```

That should solve that issue.
Note: I will have to see if gettext itself concats like that or if the po/mo->json preprocessor does that.

***

As far as we understood for differentiating locales there is no predefined structure.

So what I ended up doing, for now, is:
```javascript
// DocumentForm.js
export default withGettext(buildGettextGetTranslationsFunction('en-US'), buildGettextGetPluralFormsFunction('en-US'))(DocumentForm);
```

```javascript
// _helpers.js
export function buildGettextGetTranslationsFunction(locale = 'en-US') {
    // TODO In future we should do this here, instead of "const dictionary":
    // a.) check if the dictionary already has the locale, get it from a web service if it doesn not exist
    // b.) merge it with the existing dictionary (to have multi locale support if you switch around the UI locale)
    const dictionary = {
        'en-US' : {
            '_IDENTIFIER_': 'Identifier',
            '_IDENTIFIER_PLACEHOLDER_' : 'Helps you identifying this document for example when working in teams…',
        },
        'de-DE' : {
            '_IDENTIFIER_': 'Identifier',
            '_IDENTIFIER_PLACEHOLDER_' : 'Hilft Ihnen bei der Identifikation dieses Dokumentes z.B. während der Teamarbeit…',
        },
    }
    const getTranslationsFunction = function() {
        if (dictionary[locale] === undefined || dictionary[locale] === null) {
            logdebug("Requested locale '" + locale + "' is missing in gettext dictionary.");

            return {}; // No gettext translations found for this locale
        }

        return dictionary[locale];
    }
    return getTranslationsFunction;
}

export function buildGettextGetPluralFormsFunction(locale = 'en-US') {
    const getPluralFormsFunction = function(n) {
        return n > 1 ? 1 : 0;
    }
    return getPluralFormsFunction;
}
```

### Issue

We however do not have the locale at transpile-time.
We figure out the UI locale by a session setting we retrieve through from the app-server. That setting can however change if the user switches their locale. So before rendering aka at `componentWillMount()` we have to fetch the the correct locale. That aside if the user changes his locale we have to update whatever getTranslations() returns.

Any pointers in that regard?

**Comment by eugene-manuilov** [comment]
Hey @inoas,

if i understand your issue correctly, then i would suggest to not pass translations and plural form functions to the `withGettext` function. Add it to the component via props. So do it like this:

```js
// DocumentForm.js
export default withGettext()(DocumentForm);
```
Then in your app:

```js
// App.js
import DocumentForm from './DocumentForm';

class App extends Component {

    render() {
        const locale = 'en-US';
        return (
            <DocumentForm translations={buildGettextGetTranslationsFunction(locale)} plural={buildGettextGetPluralFormsFunction(locale) />
        );
    }

}
```

Will it work for you?

**Comment by inoas** [comment]
The higher order components are tougher to understand for me... they do not help in this case, do they?

We are going to try! This I think will also allow us to store our translation json into our store and cache it there if the user decides to switch locales.

**Comment by eugene-manuilov** [comment]
It helps. You don't need to create HOC for each component which requires translations. Just add HOC to the global component which will hold all other components and gettext functions will be available for each component via context.

**Comment by OsamaShabrez** [comment]
HOCs wrap user (dumb) components with a new component allowing us to have shared code in one place but in this case, individual components need context to get access to the functions and HOC will not pass this context to child components.

**Comment by inoas** [comment]
Currently I just have the simple issue to create a file similar to App.js but building around this

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';

import DocumentForm from './components/DocumentForm';
import documentStore from './store/documentStore';

const app = document.getElementById('flexi-cms--cms-documents--react');

ReactDOM.render(<Provider store={documentStore}>
    <DocumentForm />
</Provider>, app);

```

**Comment by inoas** [comment]
Okay so we got it down to I think only having to add these two things to our components to use the functions in a concise manner:

```
// Component PaginatorButtons.js, below export default class PaginatorButtons extends Component
PaginatorButtons.contextTypes = {
    gettext: PropTypes.func.isRequired,
    ngettext: PropTypes.func.isRequired,
    xgettext: PropTypes.func.isRequired,
    nxgettext: PropTypes.func.isRequired,
};
// within render() {}
        const { gettext, xgettext, ngettext, nxgettext } = this.context; // gettext
```
The duplication is there but now it is "okay"...
Is there a sane way to get around that?

**Comment by eugene-manuilov** [comment]
@inoas by duplication you mean that you have to enter `contextTypes` hash for every component where you want to use gettext functions? If yes, then this is how React work with context and you have to do it the same. There is no other way around. You don't need to declare all 4 functions, just add ones you need in a component.

**Comment by inoas** [comment]
That and this line `const { gettext, xgettext, ngettext, nxgettext } = this.context;`
But it is okay... limited amount of repetition.

**Comment by eugene-manuilov** [comment]
¯\_(ツ)_/¯ that's how React doing this stuff

**Comment by inoas** [comment]
Right now we can store the translations into redux, cache them there and if keys do not exist refetch them from the server etc... all great.

And we can still either go poedit+po files or database backed json translation files... all great 👍
Thanks for your support. @OsamaShabrez please close this ticket ASAP.

**Comment by eugene-manuilov** [comment]
Awesome!
